import {
	card,
	gameProgressConditionMax,
	gameProgressConditionMin,
	cardCountCondition,
} from './utils'
import { CardType, CardCategory, Card } from '.'

export const Cards: Card[] = [
	card({
		code: 'colonizer_training_camp',
		title: 'COLONIZER TRAINING CAMP',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Building, CardCategory.Jupiter],
		victoryPoints: 2,
		conditions: [gameProgressConditionMax('oxygen', 5)],
	}),
	card({
		code: 'asteroid_mining_consortium',
		title: 'ASTEROID MINING CONSORTIUM',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'deep_well_heating',
		title: 'DEEP WELL HEATING',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'cloud_seeding',
		title: 'CLOUD SEEDING',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [],

		conditions: [gameProgressConditionMin('oceans', 3)],
	}),
	card({
		code: 'search_for_life',
		title: 'SEARCH FOR LIFE',
		type: CardType.Action,
		description: '',
		cost: 3,
		categories: [CardCategory.Science],
		victoryPoints: 3,
		conditions: [gameProgressConditionMax('oxygen', 6)],
	}),
	card({
		code: "inventors'_guild",
		title: "INVENTORS' GUILD",
		type: CardType.Action,
		description: '',
		cost: 9,
		categories: [CardCategory.Science],
	}),
	card({
		code: 'martian_rails',
		title: 'MARTIAN RAILS',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'capital',
		title: 'CAPITAL',
		type: CardType.Building,
		description: '',
		cost: 26,
		categories: [CardCategory.Building, CardCategory.City],

		conditions: [gameProgressConditionMin('oceans', 4)],
	}),
	card({
		code: 'asteroid',
		title: 'ASTEROID',
		type: CardType.Event,
		description: '',
		cost: 14,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'comet',
		title: 'COMET',
		type: CardType.Event,
		description: '',
		cost: 21,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'big_asteroid',
		title: 'BIG ASTEROID',
		type: CardType.Event,
		description: '',
		cost: 27,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'water_import_from_europa',
		title: 'WATER IMPORT FROM EUROPA',
		type: CardType.Action,
		description: '',
		cost: 25,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'space_elevator',
		title: 'SPACE ELEVATOR',
		type: CardType.Action,
		description: '',
		cost: 27,
		categories: [CardCategory.Space, CardCategory.Building],
		victoryPoints: 2,
	}),
	card({
		code: 'development_center',
		title: 'DEVELOPMENT CENTER',
		type: CardType.Action,
		description: '',
		cost: 11,
		categories: [CardCategory.Building, CardCategory.Science],
	}),
	card({
		code: 'equatorial_magnetizer',
		title: 'EQUATORIAL MAGNETIZER',
		type: CardType.Action,
		description: '',
		cost: 11,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'domed_crater',
		title: 'DOMED CRATER',
		type: CardType.Building,
		description: '',
		cost: 24,
		categories: [CardCategory.Building, CardCategory.City],
		victoryPoints: 1,
		conditions: [gameProgressConditionMax('oxygen', 7)],
	}),
	card({
		code: 'noctis_city',
		title: 'NOCTIS CITY',
		type: CardType.Building,
		description: '',
		cost: 18,
		categories: [CardCategory.Building, CardCategory.City],
	}),
	card({
		code: 'methane_from_titan',
		title: 'METHANE FROM TITAN',
		type: CardType.Building,
		description: '',
		cost: 28,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 2,
		conditions: [gameProgressConditionMin('oxygen', 2)],
	}),
	card({
		code: 'imported_hydrogen',
		title: 'IMPORTED HYDROGEN',
		type: CardType.Event,
		description: '',
		cost: 16,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Earth],
	}),
	card({
		code: 'research_outpost',
		title: 'RESEARCH OUTPOST',
		type: CardType.Action,
		description: '',
		cost: 18,
		categories: [
			CardCategory.Building,
			CardCategory.City,
			CardCategory.Science,
		],
	}),
	card({
		code: 'phobos_space_haven',
		title: 'PHOBOS SPACE HAVEN',
		type: CardType.Building,
		description: '',
		cost: 25,
		categories: [CardCategory.Space, CardCategory.City],
		victoryPoints: 3,
	}),
	card({
		code: 'black_polar_dust',
		title: 'BLACK POLAR DUST',
		type: CardType.Building,
		description: '',
		cost: 15,
		categories: [],
	}),
	card({
		code: 'arctic_algae',
		title: 'ARCTIC ALGAE',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMax('temperature', -12)],
	}),
	card({
		code: 'predators',
		title: 'PREDATORS',
		type: CardType.Action,
		description: '',
		cost: 14,
		categories: [CardCategory.Animal],

		conditions: [gameProgressConditionMin('oxygen', 11)],
	}),
	card({
		code: 'space_station',
		title: 'Space Station',
		type: CardType.Action,
		description: '',
		cost: 10,
		categories: [CardCategory.Space],
		victoryPoints: 1,
	}),
	card({
		code: 'eos_chasma_national_park',
		title: 'Eos Chasma National Park',
		type: CardType.Building,
		description: '',
		cost: 16,
		categories: [CardCategory.Building, CardCategory.Plant],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('temperature', -12)],
	}),
	card({
		code: 'interstellar_colony_ship',
		title: 'Interstellar Colony Ship',
		type: CardType.Event,
		description: '',
		cost: 24,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Earth],
		victoryPoints: 4,
		conditions: [cardCountCondition(CardCategory.Science, 5)],
	}),
	card({
		code: 'security_fleet',
		title: 'Security Fleet',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Space],
	}),
	card({
		code: 'cupola_city',
		title: 'Cupola City',
		type: CardType.Building,
		description: '',
		cost: 16,
		categories: [CardCategory.Building, CardCategory.City],

		conditions: [gameProgressConditionMax('oxygen', 9)],
	}),
	card({
		code: 'lunar_beam',
		title: 'Lunar Beam',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [CardCategory.Power, CardCategory.Earth],
	}),
	card({
		code: 'optimal_aerobraking',
		title: 'Optimal Aerobraking',
		type: CardType.Action,
		description: '',
		cost: 7,
		categories: [CardCategory.Space],
	}),
	card({
		code: 'underground_city',
		title: 'Underground city',
		type: CardType.Building,
		description: '',
		cost: 18,
		categories: [CardCategory.Building, CardCategory.City],
	}),
	card({
		code: 'regolith_eaters',
		title: 'Regolith Eaters',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Microbe, CardCategory.Science],
	}),
	card({
		code: 'ghg_producing_bacteria',
		title: 'GHG Producing Bacteria',
		type: CardType.Action,
		description: '',
		cost: 8,
		categories: [CardCategory.Microbe, CardCategory.Science],

		conditions: [gameProgressConditionMin('oxygen', 4)],
	}),
	card({
		code: 'ants',
		title: 'Ants',
		type: CardType.Action,
		description: '',
		cost: 9,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMin('oxygen', 4)],
	}),
	card({
		code: 'release_of_inert_gases',
		title: 'Release of Inert Gases',
		type: CardType.Event,
		description: '',
		cost: 14,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'nitrogen-rich_asteroid',
		title: 'Nitrogen-Rich Asteroid',
		type: CardType.Event,
		description: '',
		cost: 31,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'rover_construction',
		title: 'Rover Construction',
		type: CardType.Action,
		description: '',
		cost: 8,
		categories: [CardCategory.Building],
		victoryPoints: 1,
	}),
	card({
		code: 'deimos_down',
		title: 'Deimos Down',
		type: CardType.Event,
		description: '',
		cost: 31,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'asteroid_mining',
		title: 'Asteroid Mining',
		type: CardType.Building,
		description: '',
		cost: 30,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 2,
	}),
	card({
		code: 'food_factory',
		title: 'Food Factory',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Building],
		victoryPoints: 1,
	}),
	card({
		code: 'archaebacteria',
		title: 'Archaebacteria',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMax('temperature', -18)],
	}),
	card({
		code: 'carbonate_processing',
		title: 'Carbonate Processing',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'natural_preserve',
		title: 'Natural Preserve',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Building, CardCategory.Science],
		victoryPoints: 1,
		conditions: [gameProgressConditionMax('oxygen', 4)],
	}),
	card({
		code: 'nuclear_power',
		title: 'Nuclear Power',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'lightning_harvest',
		title: 'Lightning Harvest',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Power],
		victoryPoints: 1,
		conditions: [cardCountCondition(CardCategory.Science, 3)],
	}),
	card({
		code: 'algae',
		title: 'Algae',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('oceans', 5)],
	}),
	card({
		code: 'adapted_lichen',
		title: 'Adapted Lichen',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Plant],
	}),
	card({
		code: 'tardigrades',
		title: 'Tardigrades',
		type: CardType.Action,
		description: '',
		cost: 4,
		categories: [CardCategory.Microbe],
	}),
	card({
		code: 'virus',
		title: 'Virus',
		type: CardType.Event,
		description: '',
		cost: 1,
		categories: [CardCategory.Event, CardCategory.Microbe],
	}),
	card({
		code: 'miranda_resort',
		title: 'Miranda Resort',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'fish',
		title: 'Fish',
		type: CardType.Action,
		description: '',
		cost: 9,
		categories: [CardCategory.Animal],

		conditions: [gameProgressConditionMin('temperature', 2)],
	}),
	card({
		code: 'lake_marineris',
		title: 'Lake Marineris',
		type: CardType.Building,
		description: '',
		cost: 18,
		categories: [],
		victoryPoints: 2,
		conditions: [gameProgressConditionMin('temperature', 0)],
	}),
	card({
		code: 'small_animals',
		title: 'Small Animals',
		type: CardType.Action,
		description: '',
		cost: 6,
		categories: [CardCategory.Animal],

		conditions: [gameProgressConditionMin('oxygen', 6)],
	}),
	card({
		code: 'kelp_farming',
		title: 'Kelp Farming',
		type: CardType.Building,
		description: '',
		cost: 17,
		categories: [CardCategory.Plant],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oceans', 6)],
	}),
	card({
		code: 'mine',
		title: 'Mine',
		type: CardType.Building,
		description: '',
		cost: 4,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'vesta_shipyard',
		title: 'Vesta Shipyard',
		type: CardType.Building,
		description: '',
		cost: 15,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'beam_from_a_thorium_asteroid',
		title: 'Beam from a Thorium Asteroid',
		type: CardType.Building,
		description: '',
		cost: 32,
		categories: [CardCategory.Power, CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'mangrove',
		title: 'Mangrove',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Plant],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('temperature', 4)],
	}),
	card({
		code: 'trees',
		title: 'Trees',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [CardCategory.Plant],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('temperature', -4)],
	}),
	card({
		code: 'great_escarpment_consortium',
		title: 'Great Escarpment Consortium',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [],
	}),
	card({
		code: 'mineral_deposit',
		title: 'Mineral Deposit',
		type: CardType.Event,
		description: '',
		cost: 5,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'mining_expedition',
		title: 'Mining Expedition',
		type: CardType.Event,
		description: '',
		cost: 12,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'mining_area',
		title: 'Mining Area',
		type: CardType.Building,
		description: '',
		cost: 4,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'building_industries',
		title: 'Building Industries',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'land_claim',
		title: 'Land Claim',
		type: CardType.Event,
		description: '',
		cost: 1,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'mining_rights',
		title: 'Mining Rights',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'sponsors',
		title: 'Sponsors',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'electro_catapult',
		title: 'Electro Catapult',
		type: CardType.Action,
		description: '',
		cost: 17,
		categories: [CardCategory.Building],
		victoryPoints: 1,
		conditions: [gameProgressConditionMax('oxygen', 8)],
	}),
	card({
		code: 'earth_catapult',
		title: 'Earth Catapult',
		type: CardType.Action,
		description: '',
		cost: 23,
		categories: [CardCategory.Earth],
		victoryPoints: 2,
	}),
	card({
		code: 'advanced_alloys',
		title: 'Advanced Alloys',
		type: CardType.Action,
		description: '',
		cost: 9,
		categories: [CardCategory.Science],
	}),
	card({
		code: 'birds',
		title: 'Birds',
		type: CardType.Action,
		description: '',
		cost: 10,
		categories: [CardCategory.Animal],

		conditions: [gameProgressConditionMin('oxygen', 13)],
	}),
	card({
		code: 'mars_university',
		title: 'Mars University',
		type: CardType.Action,
		description: '',
		cost: 8,
		categories: [CardCategory.Building, CardCategory.Science],
		victoryPoints: 1,
	}),
	card({
		code: 'viral_enhancers',
		title: 'Viral Enhancers',
		type: CardType.Action,
		description: '',
		cost: 9,
		categories: [CardCategory.Microbe, CardCategory.Science],
	}),
	card({
		code: 'towing_a_comet',
		title: 'Towing a Comet',
		type: CardType.Event,
		description: '',
		cost: 23,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'space_mirrors',
		title: 'Space Mirrors',
		type: CardType.Action,
		description: '',
		cost: 3,
		categories: [CardCategory.Space, CardCategory.Power],
	}),
	card({
		code: 'solar_wind_power',
		title: 'Solar Wind Power',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Power, CardCategory.Space, CardCategory.Science],
	}),
	card({
		code: 'ice_asteroid',
		title: 'Ice Asteroid',
		type: CardType.Event,
		description: '',
		cost: 23,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'quantum_extractor',
		title: 'Quantum Extractor',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Power, CardCategory.Science],

		conditions: [cardCountCondition(CardCategory.Science, 4)],
	}),
	card({
		code: 'giant_ice_asteroid',
		title: 'Giant Ice Asteroid',
		type: CardType.Event,
		description: '',
		cost: 36,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'ganymede_colony',
		title: 'Ganymede Colony',
		type: CardType.Building,
		description: '',
		cost: 20,
		categories: [CardCategory.City, CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'callisto_penal_mines',
		title: 'Callisto Penal Mines',
		type: CardType.Building,
		description: '',
		cost: 24,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 2,
	}),
	card({
		code: 'giant_space_mirror',
		title: 'Giant Space Mirror',
		type: CardType.Building,
		description: '',
		cost: 17,
		categories: [CardCategory.Space, CardCategory.Power],
	}),
	card({
		code: 'trans-neptune_probe',
		title: 'Trans-Neptune Probe',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Space, CardCategory.Science],
		victoryPoints: 1,
	}),
	card({
		code: 'commercial_district',
		title: 'Commercial District',
		type: CardType.Building,
		description: '',
		cost: 16,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'robotic_workforce',
		title: 'Robotic Workforce',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Science],
	}),
	card({
		code: 'grass',
		title: 'Grass',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('temperature', -16)],
	}),
	card({
		code: 'heather',
		title: 'Heather',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('temperature', -14)],
	}),
	card({
		code: 'peroxide_power',
		title: 'Peroxide Power',
		type: CardType.Building,
		description: '',
		cost: 7,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'research',
		title: 'Research',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Science, CardCategory.Science],
		victoryPoints: 1,
	}),
	card({
		code: 'gene_repair',
		title: 'Gene Repair',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Science],
		victoryPoints: 2,
		conditions: [cardCountCondition(CardCategory.Science, 3)],
	}),
	card({
		code: 'io_mining_industries_',
		title: 'IO Mining Industries ',
		type: CardType.Building,
		description: '',
		cost: 41,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 1,
	}),
	card({
		code: 'bushes',
		title: 'Bushes',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('temperature', -10)],
	}),
	card({
		code: 'mass_converter',
		title: 'Mass Converter',
		type: CardType.Action,
		description: '',
		cost: 8,
		categories: [CardCategory.Power, CardCategory.Science],

		conditions: [cardCountCondition(CardCategory.Science, 5)],
	}),
	card({
		code: 'physics_complex',
		title: 'Physics Complex',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Building, CardCategory.Science],
		victoryPoints: 2,
	}),
	card({
		code: 'greenhouses',
		title: 'Greenhouses',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Building, CardCategory.Plant],
	}),
	card({
		code: 'nuclear_zone',
		title: 'Nuclear Zone',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Earth],
		victoryPoints: -2,
	}),
	card({
		code: 'tropical_resort',
		title: 'Tropical Resort',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [CardCategory.Building],
		victoryPoints: 2,
	}),
	card({
		code: 'toll_station',
		title: 'Toll Station',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Space],
	}),
	card({
		code: 'fueled_generators',
		title: 'Fueled Generators',
		type: CardType.Building,
		description: '',
		cost: 1,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'ironworks',
		title: 'Ironworks',
		type: CardType.Action,
		description: '',
		cost: 11,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'power_grid',
		title: 'Power Grid',
		type: CardType.Building,
		description: '',
		cost: 18,
		categories: [CardCategory.Power],
	}),
	card({
		code: 'steelworks',
		title: 'Steelworks',
		type: CardType.Action,
		description: '',
		cost: 15,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'ore_processor',
		title: 'Ore Processor',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'earth_office',
		title: 'Earth Office',
		type: CardType.Action,
		description: '',
		cost: 1,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'acquired_company',
		title: 'Acquired Company',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'media_archives',
		title: 'Media Archives',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'open_city',
		title: 'Open City',
		type: CardType.Building,
		description: '',
		cost: 23,
		categories: [CardCategory.Building, CardCategory.City],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oxygen', 12)],
	}),
	card({
		code: 'media_group',
		title: 'Media Group',
		type: CardType.Action,
		description: '',
		cost: 6,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'business_network',
		title: 'Business Network',
		type: CardType.Action,
		description: '',
		cost: 4,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'business_contacts',
		title: 'Business Contacts',
		type: CardType.Event,
		description: '',
		cost: 7,
		categories: [CardCategory.Event, CardCategory.Earth],

		conditions: [gameProgressConditionMin('temperature', 4)],
	}),
	card({
		code: 'bribed_committee',
		title: 'Bribed Committee',
		type: CardType.Event,
		description: '',
		cost: 7,
		categories: [CardCategory.Event, CardCategory.Earth],
		victoryPoints: -2,
	}),
	card({
		code: 'solar_power',
		title: 'Solar Power',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Building, CardCategory.Power],
		victoryPoints: 1,
	}),
	card({
		code: 'breathing_filters',
		title: 'Breathing Filters',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Science],
		victoryPoints: 2,
		conditions: [gameProgressConditionMin('oxygen', 7)],
	}),
	card({
		code: 'artificial_photosynthesis',
		title: 'Artificial Photosynthesis',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Science],
	}),
	card({
		code: 'artificial_lake',
		title: 'Artificial Lake',
		type: CardType.Building,
		description: '',
		cost: 15,
		categories: [CardCategory.Building],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('temperature', -6)],
	}),
	card({
		code: 'geothermal_power',
		title: 'Geothermal Power',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'farming',
		title: 'Farming',
		type: CardType.Building,
		description: '',
		cost: 16,
		categories: [CardCategory.Plant],
		victoryPoints: 2,
		conditions: [gameProgressConditionMin('temperature', 4)],
	}),
	card({
		code: 'dust_seals',
		title: 'Dust Seals',
		type: CardType.Building,
		description: '',
		cost: 2,
		categories: [],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oceans', 3)],
	}),
	card({
		code: 'urbanized_area',
		title: 'Urbanized Area',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Building, CardCategory.City],
	}),
	card({
		code: 'sabotage',
		title: 'Sabotage',
		type: CardType.Event,
		description: '',
		cost: 1,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'moss',
		title: 'Moss',
		type: CardType.Building,
		description: '',
		cost: 4,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('oceans', 3)],
	}),
	card({
		code: 'industrial_center',
		title: 'Industrial Center',
		type: CardType.Action,
		description: '',
		cost: 4,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'hired_raiders',
		title: 'Hired Raiders',
		type: CardType.Event,
		description: '',
		cost: 1,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'hackers',
		title: 'Hackers',
		type: CardType.Building,
		description: '',
		cost: 3,
		categories: [],
		victoryPoints: -1,
	}),
	card({
		code: 'ghg_factories',
		title: 'GHG Factories',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'subterranean_reservoir',
		title: 'Subterranean Reservoir',
		type: CardType.Event,
		description: '',
		cost: 11,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'ecological_zone',
		title: 'Ecological Zone',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Plant, CardCategory.Animal],
	}),
	card({
		code: 'zeppelins',
		title: 'Zeppelins',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oxygen', 5)],
	}),
	card({
		code: 'worms',
		title: 'Worms',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMin('oxygen', 4)],
	}),
	card({
		code: 'decomposers',
		title: 'Decomposers',
		type: CardType.Action,
		description: '',
		cost: 5,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMin('oxygen', 3)],
	}),
	card({
		code: 'fusion_power',
		title: 'Fusion Power',
		type: CardType.Building,
		description: '',
		cost: 14,
		categories: [
			CardCategory.Building,
			CardCategory.Power,
			CardCategory.Science,
		],
	}),
	card({
		code: 'symbiotic_fungus',
		title: 'Symbiotic Fungus',
		type: CardType.Action,
		description: '',
		cost: 4,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMin('temperature', -14)],
	}),
	card({
		code: 'extreme-cold_fungus',
		title: 'Extreme-Cold Fungus',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMax('temperature', -10)],
	}),
	card({
		code: 'advanced_ecosystems',
		title: 'Advanced Ecosystems',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Animal, CardCategory.Microbe, CardCategory.Plant],
		victoryPoints: 3,
	}),
	card({
		code: 'great_dam',
		title: 'Great Dam',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Building, CardCategory.Power],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oceans', 4)],
	}),
	card({
		code: 'cartel',
		title: 'Cartel',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Earth],
	}),
	card({
		code: 'strip_mine',
		title: 'Strip Mine',
		type: CardType.Building,
		description: '',
		cost: 25,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'wave_power',
		title: 'Wave Power',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Power],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oceans', 3)],
	}),
	card({
		code: 'lava_flows',
		title: 'Lava Flows',
		type: CardType.Event,
		description: '',
		cost: 18,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'power_plant',
		title: 'Power Plant',
		type: CardType.Building,
		description: '',
		cost: 4,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'mohole_area',
		title: 'Mohole Area',
		type: CardType.Building,
		description: '',
		cost: 20,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'large_convoy',
		title: 'Large Convoy',
		type: CardType.Event,
		description: '',
		cost: 36,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Earth],
		victoryPoints: 2,
	}),
	card({
		code: 'titanium_mine',
		title: 'Titanium Mine',
		type: CardType.Building,
		description: '',
		cost: 7,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'tectonic_stress_power',
		title: 'Tectonic Stress Power',
		type: CardType.Building,
		description: '',
		cost: 18,
		categories: [CardCategory.Building, CardCategory.Power],
		victoryPoints: 1,
		conditions: [cardCountCondition(CardCategory.Science, 2)],
	}),
	card({
		code: '_nitrophilic_moss',
		title: ' Nitrophilic Moss',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('oceans', 3)],
	}),
	card({
		code: 'herbivores',
		title: 'Herbivores',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Animal],

		conditions: [gameProgressConditionMin('oxygen', 8)],
	}),
	card({
		code: 'insects',
		title: 'Insects',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Microbe],

		conditions: [gameProgressConditionMin('oxygen', 6)],
	}),
	card({
		code: "ceo's_favorite_project",
		title: "CEO's Favorite Project",
		type: CardType.Event,
		description: '',
		cost: 1,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'anti-gravity_technology',
		title: 'Anti-gravity Technology',
		type: CardType.Action,
		description: '',
		cost: 14,
		categories: [CardCategory.Science],
		victoryPoints: 3,
		conditions: [cardCountCondition(CardCategory.Science, 7)],
	}),
	card({
		code: 'investment_loan',
		title: 'Investment Loan',
		type: CardType.Event,
		description: '',
		cost: 3,
		categories: [CardCategory.Event, CardCategory.Earth],
	}),
	card({
		code: 'insulation',
		title: 'Insulation',
		type: CardType.Building,
		description: '',
		cost: 2,
		categories: [],
	}),
	card({
		code: 'adaptation_technology',
		title: 'Adaptation Technology',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Science],
		victoryPoints: 1,
	}),
	card({
		code: 'caretaker_contract',
		title: 'Caretaker Contract',
		type: CardType.Action,
		description: '',
		cost: 3,
		categories: [],

		conditions: [gameProgressConditionMin('temperature', 0)],
	}),
	card({
		code: 'designed_microorganisms',
		title: 'Designed Microorganisms',
		type: CardType.Building,
		description: '',
		cost: 16,
		categories: [CardCategory.Microbe, CardCategory.Science],

		conditions: [gameProgressConditionMax('temperature', -14)],
	}),
	card({
		code: 'standard_technology',
		title: 'Standard Technology',
		type: CardType.Action,
		description: '',
		cost: 6,
		categories: [CardCategory.Science],
	}),
	card({
		code: 'nitrite_reducing_bacteria',
		title: 'Nitrite Reducing Bacteria',
		type: CardType.Action,
		description: '',
		cost: 11,
		categories: [CardCategory.Microbe],
	}),
	card({
		code: 'industrial_microbes',
		title: 'Industrial Microbes',
		type: CardType.Building,
		description: '',
		cost: 12,
		categories: [CardCategory.Building, CardCategory.Microbe],
	}),
	card({
		code: 'lichen',
		title: 'Lichen',
		type: CardType.Building,
		description: '',
		cost: 7,
		categories: [CardCategory.Plant],

		conditions: [gameProgressConditionMin('temperature', -24)],
	}),
	card({
		code: 'power_supply_consortium',
		title: 'Power Supply Consortium',
		type: CardType.Building,
		description: '',
		cost: 5,
		categories: [CardCategory.Power],
	}),
	card({
		code: 'convoy_from_europa',
		title: 'Convoy From Europa',
		type: CardType.Event,
		description: '',
		cost: 15,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'imported_ghg',
		title: 'Imported GHG',
		type: CardType.Event,
		description: '',
		cost: 7,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Earth],
	}),
	card({
		code: 'imported_nitrogen',
		title: 'Imported Nitrogen',
		type: CardType.Event,
		description: '',
		cost: 23,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Earth],
	}),
	card({
		code: 'micro-mills',
		title: 'Micro-Mills',
		type: CardType.Building,
		description: '',
		cost: 3,
		categories: [],
	}),
	card({
		code: 'magnetic_field_generators',
		title: 'Magnetic Field Generators',
		type: CardType.Building,
		description: '',
		cost: 20,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'shuttles',
		title: 'Shuttles',
		type: CardType.Action,
		description: '',
		cost: 10,
		categories: [CardCategory.Space],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oxygen', 5)],
	}),
	card({
		code: 'import_of_advanced_ghg',
		title: 'Import of Advanced GHG',
		type: CardType.Event,
		description: '',
		cost: 9,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Earth],
	}),
	card({
		code: 'windmills',
		title: 'Windmills',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Building, CardCategory.Power],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('oxygen', 7)],
	}),
	card({
		code: 'tundra_farming',
		title: 'Tundra Farming',
		type: CardType.Building,
		description: '',
		cost: 16,
		categories: [CardCategory.Plant],
		victoryPoints: 2,
		conditions: [gameProgressConditionMin('temperature', -6)],
	}),
	card({
		code: 'aerobraked_ammonia_asteroid',
		title: 'Aerobraked Ammonia Asteroid',
		type: CardType.Event,
		description: '',
		cost: 26,
		categories: [CardCategory.Event, CardCategory.Space],
	}),
	card({
		code: 'magnetic_field_dome',
		title: 'Magnetic Field Dome',
		type: CardType.Building,
		description: '',
		cost: 5,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'pets',
		title: 'Pets',
		type: CardType.Action,
		description: '',
		cost: 10,
		categories: [CardCategory.Animal, CardCategory.Earth],
	}),
	card({
		code: 'protected_habitats',
		title: 'Protected Habitats',
		type: CardType.Action,
		description: '',
		cost: 5,
		categories: [],
	}),
	card({
		code: 'protected_valley',
		title: 'Protected Valley',
		type: CardType.Building,
		description: '',
		cost: 23,
		categories: [CardCategory.Building, CardCategory.Plant],
	}),
	card({
		code: 'satellites',
		title: 'Satellites',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Space],
	}),
	card({
		code: 'noctis_farming',
		title: 'Noctis Farming',
		type: CardType.Building,
		description: '',
		cost: 10,
		categories: [CardCategory.Plant, CardCategory.Building],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('temperature', -20)],
	}),
	card({
		code: 'water_splitting_plant',
		title: 'Water Splitting Plant',
		type: CardType.Action,
		description: '',
		cost: 12,
		categories: [CardCategory.Building],

		conditions: [gameProgressConditionMin('oceans', 2)],
	}),
	card({
		code: 'heat_trappers',
		title: 'Heat Trappers',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Building, CardCategory.Power],
		victoryPoints: -1,
	}),
	card({
		code: 'soil_factory',
		title: 'Soil Factory',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Building],
		victoryPoints: 1,
	}),
	card({
		code: 'fuel_factory',
		title: 'Fuel Factory',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'ice_cap_melting',
		title: 'Ice Cap Melting',
		type: CardType.Event,
		description: '',
		cost: 5,
		categories: [CardCategory.Event],

		conditions: [gameProgressConditionMin('temperature', 2)],
	}),
	card({
		code: 'corporate_stronghold',
		title: 'Corporate Stronghold',
		type: CardType.Building,
		description: '',
		cost: 11,
		categories: [CardCategory.Building, CardCategory.City],
		victoryPoints: -2,
	}),
	card({
		code: 'biomass_combustors',
		title: 'Biomass Combustors',
		type: CardType.Building,
		description: '',
		cost: 4,
		categories: [CardCategory.Building, CardCategory.Power],
		victoryPoints: -1,
		conditions: [gameProgressConditionMin('oxygen', 6)],
	}),
	card({
		code: 'livestock',
		title: 'Livestock',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Animal],

		conditions: [gameProgressConditionMin('oxygen', 9)],
	}),
	card({
		code: 'olympus_conference',
		title: 'Olympus Conference',
		type: CardType.Action,
		description: '',
		cost: 10,
		categories: [
			CardCategory.Building,
			CardCategory.Earth,
			CardCategory.Science,
		],
		victoryPoints: 1,
	}),
	card({
		code: 'rad-suits',
		title: 'Rad-Suits',
		type: CardType.Building,
		description: '',
		cost: 6,
		categories: [],
		victoryPoints: 1,
		conditions: [gameProgressConditionMin('temperature', 2)],
	}),
	card({
		code: 'aquifer_pumping',
		title: 'Aquifer Pumping',
		type: CardType.Action,
		description: '',
		cost: 18,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'flooding',
		title: 'Flooding',
		type: CardType.Event,
		description: '',
		cost: 7,
		categories: [CardCategory.Event],
		victoryPoints: -1,
	}),
	card({
		code: 'energy_saving',
		title: 'Energy Saving',
		type: CardType.Building,
		description: '',
		cost: 15,
		categories: [CardCategory.Power],
	}),
	card({
		code: 'local_heat_trapping',
		title: 'Local Heat Trapping',
		type: CardType.Event,
		description: '',
		cost: 1,
		categories: [CardCategory.Event],
	}),
	card({
		code: 'permafrost_extraction',
		title: 'Permafrost Extraction',
		type: CardType.Event,
		description: '',
		cost: 8,
		categories: [CardCategory.Event],

		conditions: [gameProgressConditionMin('temperature', -8)],
	}),
	card({
		code: 'invention_contest',
		title: 'Invention Contest',
		type: CardType.Event,
		description: '',
		cost: 2,
		categories: [CardCategory.Event, CardCategory.Science],

		conditions: [gameProgressConditionMin('temperature', 3)],
	}),
	card({
		code: 'plantation',
		title: 'Plantation',
		type: CardType.Building,
		description: '',
		cost: 15,
		categories: [CardCategory.Plant],

		conditions: [cardCountCondition(CardCategory.Science, 2)],
	}),
	card({
		code: 'power_infrastructure',
		title: 'Power Infrastructure',
		type: CardType.Action,
		description: '',
		cost: 4,
		categories: [CardCategory.Building, CardCategory.Power],
	}),
	card({
		code: 'indentured_workers',
		title: 'Indentured Workers',
		type: CardType.Event,
		description: '',
		cost: 0,
		categories: [CardCategory.Event],
		victoryPoints: -1,
	}),
	card({
		code: 'lagrange_observatory',
		title: 'Lagrange Observatory',
		type: CardType.Building,
		description: '',
		cost: 9,
		categories: [CardCategory.Space, CardCategory.Science],
		victoryPoints: 1,
	}),
	card({
		code: 'terraforming_ganymede',
		title: 'Terraforming Ganymede',
		type: CardType.Building,
		description: '',
		cost: 33,
		categories: [CardCategory.Space, CardCategory.Jupiter],
		victoryPoints: 2,
	}),
	card({
		code: 'immigration_shuttles',
		title: 'Immigration Shuttles',
		type: CardType.Building,
		description: '',
		cost: 31,
		categories: [CardCategory.Space, CardCategory.Earth],
	}),
	card({
		code: 'restricted_area',
		title: 'Restricted Area',
		type: CardType.Action,
		description: '',
		cost: 11,
		categories: [CardCategory.Science],
	}),
	card({
		code: 'immigrant_city',
		title: 'Immigrant City',
		type: CardType.Action,
		description: '',
		cost: 13,
		categories: [CardCategory.Building, CardCategory.City],
	}),
	card({
		code: 'energy_tapping',
		title: 'Energy Tapping',
		type: CardType.Building,
		description: '',
		cost: 3,
		categories: [CardCategory.Power],
		victoryPoints: -1,
	}),
	card({
		code: 'underground_detonations',
		title: 'Underground Detonations',
		type: CardType.Action,
		description: '',
		cost: 6,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'soletta',
		title: 'Soletta',
		type: CardType.Building,
		description: '',
		cost: 35,
		categories: [CardCategory.Space],
	}),
	card({
		code: 'technology_demonstration',
		title: 'Technology Demonstration',
		type: CardType.Event,
		description: '',
		cost: 5,
		categories: [CardCategory.Event, CardCategory.Space, CardCategory.Science],
	}),
	card({
		code: 'rad-chem_factory',
		title: 'Rad-Chem Factory',
		type: CardType.Building,
		description: '',
		cost: 8,
		categories: [CardCategory.Building],
	}),
	card({
		code: 'special_design',
		title: 'Special Design',
		type: CardType.Event,
		description: '',
		cost: 4,
		categories: [CardCategory.Event, CardCategory.Science],
	}),
	card({
		code: 'medical_lab',
		title: 'Medical Lab',
		type: CardType.Building,
		description: '',
		cost: 13,
		categories: [CardCategory.Building, CardCategory.Science],
		victoryPoints: 1,
	}),
	card({
		code: 'ai_central',
		title: 'AI Central',
		type: CardType.Action,
		description: '',
		cost: 21,
		categories: [CardCategory.Building, CardCategory.Science],
		victoryPoints: 1,
		conditions: [cardCountCondition(CardCategory.Science, 3)],
	}),
]
