name: Build image
concurrency: prod

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: containers.zipek.cz
          username: ${{ secrets.REPOSITORY_USERNAME }}
          password: ${{ secrets.REPOSITORY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker/Dockerfile
          tags: |
            containers.zipek.cz/kamen/open-terraforming:latest,
            containers.zipek.cz/kamen/open-terraforming:${{ github.ref_name }},
            ghcr.io/open-terraforming/open-terraforming:latest,
            ghcr.io/open-terraforming/open-terraforming:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: OT_VERSION=${{  github.ref_name }}
          platforms: linux/amd64,linux/arm64

